### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TomCallan** [TomCallan/pyine#1]
## Data Providers
- [x]  Finnhub
- [ ]  Alpha Vantage
- [ ]  TD Ameritrade

## Indicators
- [ ] Full Trading View Support

## Convert
- [x] Proof of Concept
- [ ] Deployment Ready Class Creation
- [ ] Full pyine integration 

## Miscellaneous 
- [ ] Data Formatting

**Comment by Gilocho** [comment]
Hi Tom,
interesting your code only that I would like to know if some other dependency is needed because when I try for example: from pyine import convert
marks me the following error:
    from .indicators import *
ModuleNotFoundError: No module named 'pyine.indicators'

**Comment by TomCallan** [comment]
> ModuleNotFoundError: No module named 'pyine.indicators'
This issue is caused by a problem with the pypi distribution, there should be a fix out later today. until then I recommend using the github source as it is far more up to date.
